// This file is generated by icon spritesheet generator

export type IconName =
  | "x"
  | "users"
  | "user"
  | "trophy"
  | "sun"
  | "smile-plus"
  | "shield-half"
  | "settings"
  | "search"
  | "scale"
  | "pilcrow"
  | "moon"
  | "menu"
  | "log-out"
  | "log-in"
  | "loader"
  | "list-ordered"
  | "laptop"
  | "info"
  | "home"
  | "frown"
  | "folders"
  | "folder"
  | "folder-sync"
  | "folder-plus"
  | "dices"
  | "circle-alert"
  | "chevrons-up-down"
  | "chevron-left"
  | "check"
  | "calendar"
  | "angry"

export const iconNames = [
  "x",
  "users",
  "user",
  "trophy",
  "sun",
  "smile-plus",
  "shield-half",
  "settings",
  "search",
  "scale",
  "pilcrow",
  "moon",
  "menu",
  "log-out",
  "log-in",
  "loader",
  "list-ordered",
  "laptop",
  "info",
  "home",
  "frown",
  "folders",
  "folder",
  "folder-sync",
  "folder-plus",
  "dices",
  "circle-alert",
  "chevrons-up-down",
  "chevron-left",
  "check",
  "calendar",
  "angry",
] as const
