catalogs:
  build:
    "vite": ^6.3.5
    "vite-tsconfig-paths": ^5.1.4
    "vite-plugin-devtools-json": ^0.2.0
  styling:
    "tailwindcss": ^4.1.10
    "@tailwindcss/vite": ^4.1.10
  typing:
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6
    "typescript": ^5.8.3

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
