catalogs:
  framework:
    react-router: ^7.6.3
    '@react-router/dev': ^7.6.3
    '@react-router/node': ^7.6.3
  bundler:
    vite: ^7.0.0
    '@netlify/vite-plugin-react-router': ^1.0.1
    vite-plugin-devtools-json: ^0.2.1
    vite-tsconfig-paths: ^5.1.4
  typing:
    typescript: ~5.8.3
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
    '@types/node': ^24.0.8
  styling:
    tailwindcss: ^4.1.11
    '@tailwindcss/vite': ^4.1.11
  orm:
    drizzle-kit: ^0.31.4
    drizzle-orm: ^0.44.2
    postgres: ^3.4.7
    '@electric-sql/pglite-socket': ^0.0.9

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
