catalogs:
  framework:
    react-router: ^7.6.2
    "@react-router/dev": ^7.6.2
    "@react-router/node": ^7.6.2
  bundler:
    vite: ^6.3.5
    "@netlify/vite-plugin-react-router": ^1.0.1
    vite-plugin-devtools-json: ^0.2.0
    vite-tsconfig-paths: ^5.1.4
  typing:
    typescript: ~5.8.3
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6
    "@types/node": ^24.0.4
  styling:
    tailwindcss: ^4.1.11
    "@tailwindcss/vite": ^4.1.11
  orm:
    drizzle-kit: ^0.31.3
    drizzle-orm: ^0.44.2
    postgres: ^3.4.7
    "@electric-sql/pglite-socket": ^0.0.9

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
