// This file is generated by npm run build:icons

export type IconName =
  | 'lucide/calendar'
  | 'lucide/check'
  | 'lucide/dices'
  | 'lucide/folder-sync'
  | 'lucide/folder'
  | 'lucide/folders'
  | 'lucide/home'
  | 'lucide/laptop'
  | 'lucide/log-out'
  | 'lucide/moon'
  | 'lucide/pilcrow'
  | 'lucide/scale'
  | 'lucide/search'
  | 'lucide/settings'
  | 'lucide/shield-half'
  | 'lucide/smile-plus'
  | 'lucide/sun'
  | 'lucide/trophy'
  | 'lucide/user'
  | 'lucide/users';
