// This file is generated by npm run build:icons
  
  export type IconName =
  	| "lucide/check"
	| "lucide/laptop"
	| "lucide/log-out"
	| "lucide/moon"
	| "lucide/search"
	| "lucide/settings"
	| "lucide/sun"
	| "lucide/user";
  