// This file is generated by npm run build:icons
  
  export type IconName =
  	| "lucide/calendar"
	| "lucide/check"
	| "lucide/dices"
	| "lucide/folder-sync"
	| "lucide/folder"
	| "lucide/home"
	| "lucide/laptop"
	| "lucide/log-out"
	| "lucide/moon"
	| "lucide/scale"
	| "lucide/search"
	| "lucide/settings"
	| "lucide/smile-plus"
	| "lucide/sun"
	| "lucide/user";
  